# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.define :floodlight do |config|
   config.vm.box = "precise64"
   config.vm.network :private_network, ip: "192.168.33.11"
   config.vm.hostname = "floodlight-node"
   config.vm.network :private_network, ip: "192.168.56.3"
   config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
   end
   config.vm.provision :shell, :path => "provision.sh"
 end

end
