# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :devstack do |vm_config|
    vm_config.vm.box = "precise64"
    vm_config.vm.hostname = "devstack"
    vm_config.vm.synced_folder "../commonData", "/Shared"
    vm_config.vm.network "private_network", ip: "10.0.2.15"
    vm_config.vm.network :forwarded_port, guest: 22, host: 2231, id: "ssh"
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision :shell, :path => "provision.sh"
end
